### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by Thomas84** [johnpierson/RhythmForDynamo#28]
**Describe the bug**
in Dynamo there is an error in the log and I cannot place nodes anymore, as soon as the rhythm package is active. 

look at line 80, 82, 85, 87
[rhythm_conflict_library.txt](https://github.com/johnpierson/RhythmForDynamo/files/5178571/rhythm_conflict_library.txt)

Translation:
During the loading of the Assembly RhythmRevit, Version=2020.7.25.0, Culture=neutral, PublicKeyToken=null Dynamo has recoginzed, that the dependency AdWindows, Version=2018.11.1.0, Culture=neutral, PublicKeyToken=null is already loaded with an incompatible version. This Assembly is probably loaded in another Revit Add-in. Please uninstall other add-ins and restart Dynamo. Dynamo is in this state probably instable. 
The incompatible version was probably loaded for one of the following assemblies:
UIFrameworkInterop, UIFramework, UIFrameworkServices, AdApplicationFrame, FabricationPartBrowser, RevitAPIUI, Autodesk.Revit.CloudRendering.Application, ConnectedDesktopUI, ContentDelivery, pyRevit_2021_982a2a80208ff7f8_PyRevitLabs.PyRevit.Runtime

The same with Xceed.Wpf.AvalonDock, Version=3.8.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4 used probably by UIFramework, pyRevit_2021_982a2a80208ff7f8_PyRevitLabs.PyRevit.Runtime, Microsoft.GeneratedCode

I will ask Ehsan to have look at this report, too. Thanks John!

**My setup**
- Operating System: win10
- Dynamo version: Build 2.6.1.8786
- Rhythm version: 2020.7.25.0
- Revit version: 2021.1 
- pyRevit version: 4.7.6

**Comment by Thomas84** [comment]
As soon as I deactivate pyRevit addin, I can place rhythm nodes and Dynamo works as expected, but there is still the error in the log (without mentioning the pyRevit addin).
[pyrevitdeactivated.txt](https://github.com/johnpierson/RhythmForDynamo/files/5182383/pyrevitdeactivated.txt)
![image](https://user-images.githubusercontent.com/5624034/92373985-70eb0a80-f0ff-11ea-8357-24f3c5a17b19.png)

After activating pyRevit again:
![image](https://user-images.githubusercontent.com/5624034/92374403-f373ca00-f0ff-11ea-85cc-f53d6deef397.png)

**Comment by johnpierson** [comment]
So I believe the AdWindows is ignorable and not the one that is causing the main error here.

A way to test this would be to remove the view extension XML in the extra folder. 

I have had numerous issues when referencing Xceed Toolkit as Dynamo uses a different version than Revit and PyRevit uses a different version too. It's a mess.

**Comment by Thomas84** [comment]
ok, I have renamed it to Rhythm_ViewExtensionDefinition._xml
The AdWindows error is still there and it seems there are still Xceed.Wpf errors (also other packages and view extensions are generating errors as soon as I activate them) 
[errors_rhythmVEdeactivated.txt](https://github.com/johnpierson/RhythmForDynamo/files/5189732/errors_rhythmVEdeactivated.txt)

But only if pyRevit is active, I cannot place any nodes

**Comment by johnpierson** [comment]
Yeah, the dependency thing is not fun at all. But, I have published a new version of Rhythm that has no dependency on Xceed. Try this one out too and it should remove the error for Rhythm pertaining to Xceed.
![image](https://user-images.githubusercontent.com/15744724/92507183-cf79bc80-f1c3-11ea-9d3c-de02a6096874.png)


---

An additional part of this that is extremely difficult is that Dynamo shows those errors for stuff that can be ignored too. Take Rhythm for example. Right now, I support Revit 2018-2021. That means Rhythm needs to reference some sort of DLL for the API, and in my case, that is the lowest common denominator, 2018. This means that the moment you open Dynamo in something higher than 2018 you will see an error that, "Rhythm loaded an older version of RevitAPI.dll" or whatever.

That is why I say that a large number of these errors are ignorable. Because referencing an old Revit DLL is _mostly_ going to be safe. Xceed is a special case because it renders the UI for Dynamo. So when a clash happens, Dynamo naturally takes a fall.

Unfortunately, I think this is a bigger issue than I can solve and should be brought up to the team, (reference this post perhaps).

**Comment by Thomas84** [comment]
true. I have updated the rhythm package and your wpf error is gone, but pyRevit creates still a conflict. I will report it to the Dynamo team. Thanks John for your help! (
[errors_dynamo_freezingWithPyRevit.txt](https://github.com/johnpierson/RhythmForDynamo/files/5189986/errors_dynamo_freezingWithPyRevit.txt)

**Comment by johnpierson** [comment]
I do think it is related to this, https://github.com/DynamoDS/Dynamo/issues/8269

**Comment by mjkkirschner** [comment]
Hi @Thomas84 @johnpierson - Is there a relevant pyRevit issue for this conflict?

**Comment by johnpierson** [comment]
not that I know of. But I am not an avid pyrevit user, so I may not be the best person to weigh in.
